config/routes.rb
Twitter::Application.routes.draw do

  devise_for :users, :controllers => {:registrations => 'users/registrations'}
  devise_for :users
  match '/tweets/get/:id' => 'tweets#get', :as => 'get_tweets'
  resources :tweets
  resources :friendships, :only => [:destroy, :create]
  match '/users/:id' => 'users#show', :as => 'user'
  match '/users/:id/following' => 'users#following', :as => 'following'
  match '/users/:id/followers' => 'users#followers', :as => 'followers'
  match '/users/get/:id' => 'users#get', :as => 'get_users'
  resources :users do
    resources :tweets
  end

  root :to => 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :avatar, :name, :email, :password, :password_confirmation, :remember_me
  has_many :tweets
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :friended, :through => :inverse_friendships, :source => :user
  validates_presence_of :name

  scope :paginate, lambda {|max| where(:id => (User.first.id...max))}
  scope :lastest, order("created_at DESC")
  scope :newest, order("created_at ASC")

  has_attached_file :avatar, :styles => {:small => "32x32#", :medium => "48x48#", :big => "128x128#"}

  def timeline(feedline = false)
    if feedline == true
      Tweet.feedline(self)
    else
      Tweet.userline(self)
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def create
    if verify_recaptcha
      super
    else
      build_resource
      resource.valid?
      resource.errors.add(:base, "Invalid recaptcha code. Please re-enter the code.")
      clean_up_passwords(resource)
      render_with_scope :new
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :unless_signed_in?, :only => [:index]
  def index
    @user = current_user
    @tweet = Tweet.new
    if user_signed_in?
      @tweets = @user.timeline(true).lastest.limit(10)
    end
    respond_to do |format|
      format.html
      format.json { render json: @tweets }
    end
  end

  def get
    @user = User.find(params[:id])
    max = params[:max_id].to_i
    limit = params[:limit].to_i
    if params[:feed] == "following"
      @users = @user.friendships.includes(:user).paginate(max).limit(limit).order("created_at DESC")
    elsif params[:feed] == "followers"
      @users = @user.inverse_friendships.includes(:user).paginate(max).limit(limit).order("created_at DESC")
    end
    (pagination = true) if @users.length <= 0
    respond_to do |format|
      unless pagination
        if params[:feed] == "following"
          format.html { render :partial => "friendships/following", :collection => @users }
        elsif params[:feed] == "followers"
          format.html { render :partial => "friendships/followers", :collection => @users }
        end
       else
        format.html {render :text => '<script>pagination = false;</script>'}
      end
      format.json { render json: @users}
    end
  end

  def following
    @user = User.find(params[:id])
    @following = @user.friendships.includes(:user).lastest
    respond_to do |format|
      format.html
      format.json { render json: @following }
    end
  end

  def followers
    @user = User.find(params[:id])
    @followers = @user.inverse_friendships.includes(:user).lastest
    respond_to do |format|
      format.html
      format.json { render json: @followers }
    end
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.timeline(false).lastest.limit(10)
    respond_to do |format|
      format.html
    end
  end

  private
  def unless_signed_in?
    redirect_to new_user_session_path unless user_signed_in?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def you_are(user)
    (user_signed_in? && current_user == user) ? "You" : user.name
  end
end

app/views/users/components/_friends.html.erb
<div class="activity">
  <h3><%= link_to "#{@user.friends.count} Following", following_path(@user) %></h3>
  <p>
  <% @user.friends.order("friendships.created_at DESC").limit(4).each do |user| %>
    <%= link_to image_tag(user.avatar.url(:small)), user_path(user) %>
  <% end %>
</p>
</div>

<div class="activity right">
  <h3><%= link_to "Followers: #{@user.friended.count}", followers_path(@user) %></h3>
<p>
  <% @user.friended.order("friendships.created_at DESC").limit(4).each do |user| %>
    <%= link_to image_tag(user.avatar.url(:small)), user_path(user) %>
  <% end %>
</p>
</div>

app/views/users/components/_profile.html.erb
<div class="component">
 <div class="profile">
   <div class="details">
     <div class="image">
       <%= image_tag(user.avatar.url(:medium)) %>
     </div>
     <div class="full-name">
       <h3><%= user.name %></h3>
     </div>
   </div>
 </div>
</div>
<div style="clear:both;"></div>
<div class="component">
 <%= render 'users/components/friends', :user => user %>
 <%= follow_button(current_user, user) %>
</div>